version: '3.8'

services:
  # 1. Tu aplicación FastAPI
  backend:
    build: .  # Construye usando el Dockerfile de la carpeta actual
    container_name: network_watcher_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    # Montamos el código como volumen para que si cambias algo en el código, 
    # se actualice sin reconstruir la imagen (Hot Reload)
    volumes:
      - ./app:/app/app

  # 2. Base de datos Postgres Local
  db:
    image: postgres:15-alpine
    container_name: network_watcher_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=network_watcher_local
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 3. Redis Local
  redis:
    image: redis:alpine
    container_name: network_watcher_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

# Volúmenes para que los datos no se borren al apagar docker
volumes:
  postgres_data:
  redis_data: