name: network-watcher
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - fastapi
  - uvicorn
  - sqlalchemy
  - psycopg2  # Conda maneja mejor los binarios de postgres que pip
  - asyncpg   # Para conexiones as√≠ncronas a SQL
  - redis-py  # Cliente de Redis
  - pydantic-settings
  - python-dotenv
